### ISSUE TITLE
Failure Compiling on Windows 10: No method named `display`

### ISSUE THREAD

**Issue by nevi-me** [alexcrichton/proc-macro2#108]
I'm trying to use wasm-bindgen, which depends on proc-macro2 **0.4.9**, but I'm getting the below error:

```rust
   Compiling proc-macro2 v0.4.9
error[E0599]: no method named `display` found for type `&syntax_pos::FileName` in the current scope
   --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-0.4.9\src\unstable.rs:290:52
    |
290 |         let filename = stable::file_name(sf.path().display().to_string());
    |                                                    ^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `proc-macro2`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I was building my project (an unmodified Hello World) as per https://rustwasm.github.io/wasm-bindgen/basic-usage.html with `cargo +nightly build --target wasm32-unknown-unknown`

Is this a known issue, or am I doing something wrong on my side? Thanks

## Environment (`rustup show`)

Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

nightly-2018-05-15-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.29.0-nightly (12ed235ad 2018-07-18)

**Comment by nevi-me** [comment]
I see that the error is caused by https://github.com/alexcrichton/proc-macro2/commit/9f0a28a9c95d59c6969dd05121115884138dede4, which was the reason for `0.4.9`. I'm updating my nightly to `2018-07-21-, I'll revert back if the issue still persists.

**Comment by nevi-me** [comment]
Updating to latest nightly fixed the problem
