### ISSUE TITLE
nightly error[E0599]: no method named `extend` found for type `&mut proc_macro::TokenStream` in the current scope

### ISSUE THREAD

**Issue by lazyuser** [alexcrichton/proc-macro2#124]
```
$ rustc --version
rustc 1.30.0-nightly (73c78734b 2018-08-05)
```

cargo build in master (0.4.16) results in
```
error[E0599]: no method named `extend` found for type `&mut proc_macro::TokenStream` in the current scope
   --> src/unstable.rs:213:21
    |
213 |                 tts.extend(
    |                     ^^^^^^

error[E0599]: no method named `extend` found for type `&mut proc_macro::TokenStream` in the current scope
   --> src/unstable.rs:228:21
    |
228 |                 tts.extend(streams.into_iter().map(|stream| stream.unwrap_nightly()))
    |                     ^^^^^^
```

**Comment by lazyuser** [comment]
git bisect results (ce0904dc1a48c05c6f97e63d047c69610675da2a is the first bad commit):
```
ce0904dc1a48c05c6f97e63d047c69610675da2a is the first bad commit
commit ce0904dc1a48c05c6f97e63d047c69610675da2a
Author: Alex Crichton <alex@alexcrichton.com>
Date:   Mon Aug 27 17:29:49 2018 -0700

    Automatically use rich API on 1.30.0+
    
    This commit detects the rustc version in the build script of proc-macro2
    to determine whether the compiler supports the necessary backend APIs.
    This should hopefully allow the crate to compile on stable by default
    but have a better implementation on 1.30.0+ compilers.
```

**Comment by dtolnay** [comment]
I am closing because we do not support old nightly compilers. It should work if you use the most recent nightly compiler. Generally "nightly" means that you upgrade the compiler "every night" if you want to be pulling in library changes because it is not possible for libraries to support a range of nightly versions.

**Comment by lazyuser** [comment]
Got it, thanks. Meanwhile I rollback to v0.4.13 until the next compiler upgrade.
