### ISSUE TITLE
1.0.11 doesn't build on rustc stable 1.43 with bindgen v0.53.2

### ISSUE THREAD

**Issue by Xaeroxe** [alexcrichton/proc-macro2#221]
```
error[E0433]: failed to resolve: use of undeclared type or module `proc_macro`
  --> /home/jacobkiesel/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.11/src/detection.rs:59:37
   |
59 |     let works = panic::catch_unwind(proc_macro::Span::call_site).is_ok();
   |                                     ^^^^^^^^^^ use of undeclared type or module `proc_macro`

```

Reproduction instructions:
1. clone bindgen
2. checkout bindgen v0.53.2
3. cargo update (Cargo.lock is checked in, but that's not how this is used in the field)
4. cargo check

This seems to be a semver breakage, though the exact nature of how it happened is beyond me as of this writing.

**Comment by dtolnay** [comment]
Thanks, fixed in 1.0.12. Apparently our CI build is borked (#222).
